# Generated by Django 3.2.14 on 2022-12-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('publication', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'BOOK_MASTER',
            },
        ),
    ]
